In [45]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity="all"
%matplotlib inline
import  matplotlib
import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets,linear_model
from sklearn.model_selection import train_test_split
import pandas as pd
#Load csv and columns
df=pd.read_csv("BankNote_dataset/data_banknote_authentication.csv")
df.head()

Variance of Wavelet Transformed image  \
0                                3.62160   
1                                4.54590   
2                                3.86600   
3                                3.45660   
4                                0.32924   

   Skewness of Wavelet Transformed image  \
0                                 8.6661   
1                                 8.1674   
2                                -2.6383   
3                                 9.5228   
4                                -4.4552   

   Kurtosis of Wavelet Transformed image  Entropy of image  Class  
0                                -2.8073          -0.44699      0  
1                                -2.4586          -1.46210      0  
2                                 1.9242           0.10645      0  
3                                -4.0112          -3.59440      0  
4                                 4.5718          -0.98880      0

In [46]:
df['Class'].value_counts()

0    762
1    610
Name: Class, dtype: int64

In [47]:
y=df.Class
X=df.drop('Class',axis=1)
X.head()
X.tail()
y.head()

Variance of Wavelet Transformed image  \
0                                3.62160   
1                                4.54590   
2                                3.86600   
3                                3.45660   
4                                0.32924   

   Skewness of Wavelet Transformed image  \
0                                 8.6661   
1                                 8.1674   
2                                -2.6383   
3                                 9.5228   
4                                -4.4552   

   Kurtosis of Wavelet Transformed image  Entropy of image  
0                                -2.8073          -0.44699  
1                                -2.4586          -1.46210  
2                                 1.9242           0.10645  
3                                -4.0112          -3.59440  
4                                 4.5718          -0.98880

Variance of Wavelet Transformed image  \
1367                                0.40614   
1368                               -1.38870   
1369                               -3.75030   
1370                               -3.56370   
1371                               -2.54190   

      Skewness of Wavelet Transformed image  \
1367                                1.34920   
1368                               -4.87730   
1369                              -13.45860   
1370                               -8.38270   
1371                               -0.65804   

      Kurtosis of Wavelet Transformed image  Entropy of image  
1367                                -1.4501          -0.55949  
1368                                 6.4774           0.34179  
1369                                17.5932          -2.77710  
1370                                12.3930          -1.28230  
1371                                 2.6842           1.19520

0    0
1    0
2    0
3    0
4    0
Name: Class, dtype: int64

In [67]:
train_X,test_X,train_y,test_y=train_test_split(X,y,train_size=0.2,random_state=123,stratify=y)

C:\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2026: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


In [68]:
train_y.head()
train_y.count()
train_y.describe()

982    1
891    1
166    0
558    0
865    1
Name: Class, dtype: int64

274

count    274.000000
mean       0.445255
std        0.497903
min        0.000000
25%        0.000000
50%        0.000000
75%        1.000000
max        1.000000
Name: Class, dtype: float64

In [97]:
from sklearn.tree import DecisionTreeClassifier, export_graphviz
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [98]:
classifier = DecisionTreeClassifier()
classifier.fit(train_X,train_y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [99]:
pred_y=classifier.predict(test_X)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(test_y, pred_y)
print(cm)

[[579  31]
 [ 19 469]]


In [100]:
accuracy = metrics.accuracy_score(test_y,pred_y)
print("Accuracy : %s" % "{0:.3%}".format(accuracy))

Accuracy : 95.446%


In [101]:
classifier = GaussianNB()
classifier.fit(train_X,train_y)

GaussianNB(priors=None)

In [102]:
pred_y=classifier.predict(test_X)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(test_y, pred_y)
print(cm)

[[543  67]
 [ 89 399]]


In [103]:
accuracy = metrics.accuracy_score(test_y,pred_y)
print("Accuracy : %s" % "{0:.3%}".format(accuracy))

Accuracy : 85.792%


In [104]:
classifier = SVC()
classifier.fit(train_X,train_y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [105]:
pred_y=classifier.predict(test_X)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(test_y, pred_y)
print(cm)

[[610   0]
 [  0 488]]


In [106]:
accuracy = metrics.accuracy_score(test_y,pred_y)
print("Accuracy : %s" % "{0:.3%}".format(accuracy))

Accuracy : 100.000%


In [107]:
classifier =LogisticRegression()
classifier.fit(train_X,train_y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [108]:
pred_y=classifier.predict(test_X)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(test_y, pred_y)
print(cm)

[[603   7]
 [  5 483]]


In [109]:
accuracy = metrics.accuracy_score(test_y,pred_y)
print("Accuracy : %s" % "{0:.3%}".format(accuracy))

Accuracy : 98.907%
